import Head from 'next/head';
import Header from './components/header';
import Footer from './components/footer';
import Project from './components/project';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sofyan RS - Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main>
        <div className="content-type-1 with-bg">
            <div className="container">
                <div className="intro">
                    <span className="hi">Hi, I am</span>
                    <h2>SOFYAN RUDIANA SYAMSI</h2>
                    <span className="status">Electronics Engineer & Web Developer</span>
                </div>
            </div>
        </div>
        <div className="content-type-2">
            <div className="container">
                <div className="about">
                    <h3 id="about">About Me</h3>
                    <p className="justify me">I am a Fresh Graduate Associate Degree of Electronics Engineering, graduate from Bandung State Polytechnic. I like technology-related things such as electronics, computer, microcontrollers, Internet of Things, AI, Machine Learning, and Website Development. Have experience working as a Freelance Wordpress Developer.</p>
                    <span className="skills">Skills</span>
                    <p><b>Non-Technical : </b>Teamwork, Creativity, Problem Solving</p>
                    <p><b>Technical : </b>Electronics, SketchUp, Autocad, Altium PCB, SCADA, HMI, PLC, IoT, Wordpress, Git, Firebase</p>
                    <p><b>Progamming Language : </b>Arduino, PHP, HTML, CSS, JavaScript, SQL, Node.js, ReactJS, NextJS</p>
                </div>
            </div>
        </div>
        <div className="content-type-1">
            <div className="container">
                <div className="project">
                    <h3 id="project">My Project</h3>
                    <div className="project-list">
                        <Project url="https://kdevz.net" title="KDevz" description="Website Penjualan Tema Custom untuk Wordpress" />
                        <Project url="https://youtu.be/j9w5XC4o9JE" title="Proyek Mandiri SKL" description="Sistem Kendali Pengatur Suhu Inkubasi Telur dengan Metode PID" />
                        <Project url="https://youtu.be/jquj6YxCuHM" title="Sequential Project SKTT" description="Sistem Pendistribusian Barang berbasis PLC Mitsubishi Conveyor FZ20" />
                        <Project url="https://youtu.be/Emyd6zTfdao" title="Proyek Mandiri SKTT" description="Sistem Kendali dan Monitoring Suhu pada Inkubasi Telur berbasis HMI SCADA" />
                        <Project url="https://pintu-air.kdevz.net/" title="Proyek Tugas Akhir" description="Sistem Kendali dan Monitoring Simulasi Pintu Air Otomatis Berbasis Internet of Things" />
                        <Project url="https://www.hmepolban.com/" title="Web HME" description="Website Himpunan Mahasiswa Elektronika Polban" />
                        <Project url="https://pameran.hmepolban.com/" title="Pameran TA Online" description="Website Pameran Alat TA Teknik Elektronika Polban" />
                        <Project url="https://kpp.hmepolban.com/" title="E-Vote HME" description="Website Pemilihan Ketua Himpunan Mahasiswa Elektronika Polban" />
                        <Project url="https://lppm.unisba.ac.id/" title="LPPM UNISBA" description="Website Lembaga Penelitian dan Pengabdian kepada Masyarakat (LPPM) Universitas Islam Bandung" />
                        <Project url="https://pokedex-kdevz.netlify.app/" title="Pokedex App" description="Website Pokedex sederhana dibuat menggunakan React.js dan PokeAPI" />
                    </div>
                </div>
            </div>
        </div>
      </main>
      <Footer/>
    </div>
  )
}
